### ISSUE TITLE
Can't build image from Dockerfile (latest)

### ISSUE THREAD

**Issue by stumpdk** [artburkart/nginx-php-fpm-phalcon#1]
Thank you for a nice Dockerfile, that I've been using alot lately.
I'm now in a situation where I need to apt-get install a new package, and therefore I'm trying to build an image based on the Dockerfile.
But when I run the build command (using Docker for Windows), I get an error.

Command: 

> docker build -t my_image --no-cache .

Error:

> /bin/sh: apt-get: not found
> The command '/bin/sh -c apt-get update &&   apt-get install -y --no-install-recommends php5-dev re2c make libpcre3-dev software-properties-common &&   add-apt-repository ppa:ondrej/php5 -y &&   apt-get update -y &&   apt-get upgrade -y &&   apt-get install php5 -y -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confold" &&   git clone git://github.com/phalcon/cphalcon.git &&   cd /cphalcon/ext &&   ./install &&   apt-get remove --purge -y software-properties-common make &&   apt-get autoremove -y &&   apt-get clean &&   apt-get autoclean &&   echo -n > /var/lib/apt/extended_states &&   rm -rf /var/lib/apt/lists/* &&   rm -rf /usr/share/man/?? &&   rm -rf /usr/share/man/??_* &&   cd / && rm -rf /cphalcon' returned a non-zero code: 127

Am I doing something completely wrong?

**Comment by artburkart** [comment]
@stumpdk - My apologies for the late response. It's been a long long time since I've looked at this Dockerfile. I'll see if I can maybe figure out what's up.

**Comment by artburkart** [comment]
@stumpdk - It would appear the image I used to depend on is no longer debian-based. Instead it uses alpine which does not use apt-get. 

Unfortunately, I can't simply point to the last version of the image that still used ubuntu because their builds were not versioned on DockerHub. This commit contains that latest of their stuff that should work with my stuff: https://github.com/ngineered/nginx-php-fpm/commit/9e216a395fa500d82394b466ef85a43a037d55e4
Since I'm not using this image anymore, I probably won't be updating it to comply with an alpine distro.

As for your needs, instead of trying to rebuild my image from scratch, you could use my image as the foundation for the new one you're building. That way, you'd still have `apt-get` available to add your new package.

I hope that helps! I'm sorry I don't have a better answer.
